spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///award?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    cache: false
#  main:
#    lazy-initialization: true

devtools:
  restart:
    additional-paths: resources/**,static/**,templates/**, permision/**, mapper/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.xhui.awardsystem.model.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    xyz:
      xhui:
        awardsystem:
          dao: debug

myConf:
  uploadPath: D:\test\