spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test2?useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
  thymeleaf:
    cache: false

devtools:
  restart:
    additional-paths: resources/**,static/**,templates/**, permision/**, mapper/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.xhui.awardsystem.model

logging:
  level:
    xyz:
      xhui:
        awardsystem:
          dao:
            mybatis: debug
